version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    container_name: django_db
    user: "1000:1000"
    volumes:
      - django_db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ONETIME_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_HOST

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    container_name: django_db_admin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST
      - MYSQL_ROOT_PASSWORD

  # python
#  django:
#    depends_on:
#      - db
#    container_name: bot
#    restart: always
#    build:
#      context: app
#      dockerfile: ../Dockerfile
#    environment:
#      - DB_HOST



volumes:
  django_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/django_db"
