# Generated by Django 4.1.7 on 2023-03-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
    ]
