# Generated by Django 4.1.7 on 2023-03-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_rename_full_name_worker_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eployment_date',
            new_name='hire_date',
        ),
    ]
